### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by nyaray** [toggl/komposable-architecture#23]
Hi,

We were looking at using this but noticed that Store has a method called `dispatch` whereas TCA nomenclature for it, as far as we understood it, was `send`, is there any reason in particular for this difference? It was rather confusing when some of us had (some) previous knowledge from iOS examples and were trying to make our way through the Android TODO app example.

Thank you!

**Comment by heytherewill** [comment]
When I was at Toggl there was a discussion about naming, because this implementation borrows concepts from TCA, Elm and MVU. I'm no longer at Toggl, so I don't remember what was the outcome of those discussions, but I believe that consistency here would be pretty beneficial, specially for the sake of achieving a single engineer vocabulary when using TCA on both platforms.

**Comment by jonekdahl** [comment]
Would the committers in this repo be open to a PR that aligns the naming conventions with the TCA terminology?

**Comment by semanticer** [comment]
I personally like dispatch more but I agree consistency is more important here.

@jonekdahl sure, feel free. Otherwise, I'll do it when I find some time. I'd add `@Deprecated` annotations for old methods with `replaceWith` parameter before we delete those methods completely in one of the upcoming releases.

**Comment by jonekdahl** [comment]
@semanticer I have opened a PR to change the name.
