### ISSUE TITLE
Return merged effect from reducers rather than a list of effects

### ISSUE THREAD

**Issue by semanticer** [toggl/komposable-architecture#51]
## Description
TCA's reducers only [return one effect](https://github.com/pointfreeco/swift-composable-architecture/blob/77dee2dc0b1186e5bb20d80173509233d95d03c6/Sources/ComposableArchitecture/Reducer.swift#L205) instead of a list of effects as we do. Instead of returning multiple effects, effects are being [merged](https://github.com/pointfreeco/swift-composable-architecture/blob/77dee2dc0b1186e5bb20d80173509233d95d03c6/Sources/ComposableArchitecture/Effect.swift#L222). 
This will probably require a bigger refactor where we should also introduce Effect as a case class with `None` case.

TODO: needs more details

## Definition of done
- [ ] TODO

**Comment by sveltema** [comment]
I've always been curious of the choice of using a single suspending fun for effects instead of using a Flow which gets you merge, concatenate, mapping, flatmap, etc etc for "free".  With a Flow you can include a `CoroutineScope` in an Action from say a ViewModel and scope the resultant effect to provide automatic cancellation for long running effects, or more direct methods of cancellation by ids.

Am I mistaken in the impression that when you start merging suspending functions for Effects, you might as well be using Flows from the very beginning?

**Comment by semanticer** [comment]
Yeah, I think effects should run on flows for sure, and we can provide multiple builders allowing users to specify their effects as flows or suspending functions depending on their needs. I'm also going to create a separate issue of effects cancelation.

**Comment by heytherewill** [comment]
> I've always been curious of the choice of using a suspending fun for effects instead of using a Flow

The historical reason is we had time constraints and didn't think this through at the time 😂 
Glad to see this getting revisited and using Flow is 100% the correct decision

**Comment by semanticer** [comment]
This was closed by #65
